source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.0.1'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
  gem 'sdoc', require: false
end
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'unicorn'


# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'cucumber', '~> 1.3.8'
gem 'cucumber-rails'
gem 'cucumber-rails-training-wheels'
gem 'rspec'
gem 'rspec-rails'
gem 'autotest'
gem 'spork'
gem 'metric_fu'
gem 'debugger'
gem 'timecop', '~> 0.6.3'
gem 'chronic', '~> 0.9.1'
# for app development...
gem 'omniauth'
gem 'omniauth-twitter'
gem 'nokogiri'
gem 'themoviedb', '~> 0.0.17'
gem 'ruby-graphviz'
gem 'reek'
gem 'flog'
gem 'flay'